language: python
python:
  - "3.5"
  
before_install:  
   - wget https://github.com/mozilla/geckodriver/releases/download/v0.16.0/geckodriver-v0.16.0-linux64.tar.gz 
   - mkdir geckodriver && tar zxvf geckodriver-v0.16.0-linux64.tar.gz -C geckodriver 
   - export PATH=$PATH:$PWD/geckodriver 
   
install:
  - pip install -r requirements.txt
  
script:
  - pytest
